<?php

/**
 * This is the model base class for the table "groups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Groups".
 *
 * Columns in table "groups" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $is_active
 * @property string $extra
 * @property string $created
 * @property string $modified
 *
 */
abstract class BaseGroups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'groups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Groups|Groups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('name, extra', 'length', 'max'=>255),
			array('created, modified', 'safe'),
			array('name, is_active, extra, created, modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, is_active, extra, created, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'is_active' => Yii::t('app', 'Is Active'),
			'extra' => Yii::t('app', 'Extra'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('extra', $this->extra, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}