<?php

/**
 * This is the model base class for the table "contacts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contacts".
 *
 * Columns in table "contacts" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $group_id
 * @property string $firstname
 * @property string $lastname
 * @property string $contact_no
 * @property string $email
 * @property string $created
 * @property string $modified
 *
 */
abstract class BaseContacts extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contacts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contacts|Contacts', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id, group_id', 'numerical', 'integerOnly'=>true),
			array('firstname, lastname', 'length', 'max'=>50),
			array('contact_no', 'length', 'max'=>20),
			array('email', 'length', 'max'=>100),
			array('created, modified', 'safe'),
			array('group_id, firstname, lastname, contact_no, email, created, modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, group_id, firstname, lastname, contact_no, email, created, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'group_id' => Yii::t('app', 'Group'),
			'firstname' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'email' => Yii::t('app', 'Email'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('group_id', $this->group_id);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('contact_no', $this->contact_no, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}