<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $firstname
 * @property string $lastname
 * @property string $gender
 * @property string $dob
 * @property string $contact_no
 * @property integer $is_active
 * @property integer $is_deleted
 * @property string $created
 * @property string $modified
 *
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password, email', 'required'),
			array('is_active, is_deleted', 'numerical', 'integerOnly'=>true),
			array('username, password, email', 'length', 'max'=>70),
			array('firstname, lastname', 'length', 'max'=>50),
			array('gender', 'length', 'max'=>6),
			array('contact_no', 'length', 'max'=>20),
			array('dob, created, modified', 'safe'),
			array('firstname, lastname, gender, dob, contact_no, is_active, is_deleted, created, modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, email, firstname, lastname, gender, dob, contact_no, is_active, is_deleted, created, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'firstname' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'gender' => Yii::t('app', 'Gender'),
			'dob' => Yii::t('app', 'Dob'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'is_active' => Yii::t('app', 'Is Active'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'created' => Yii::t('app', 'Created'),
			'modified' => Yii::t('app', 'Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('dob', $this->dob, true);
		$criteria->compare('contact_no', $this->contact_no, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}